version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend1
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./frontend:/app
